FairRootGroup/FairMQ

fairmq/FairMQChannel.cxx
fairmq/FairMQChannel.h
fairmq/FairMQDevice.cxx
fairmq/FairMQDevice.h
fairmq/FairMQMessage.h
fairmq/FairMQTransportFactory.h
fairmq/Transports.h
fairmq/nanomsg/FairMQMessageNN.cxx
fairmq/nanomsg/FairMQMessageNN.h
fairmq/nanomsg/FairMQTransportFactoryNN.cxx
fairmq/nanomsg/FairMQTransportFactoryNN.h
fairmq/options/FairMQParser.cxx
fairmq/options/FairMQProgOptions.cxx
fairmq/shmem/FairMQMessageSHM.cxx
fairmq/shmem/FairMQMessageSHM.h
fairmq/shmem/FairMQTransportFactorySHM.cxx
fairmq/shmem/FairMQTransportFactorySHM.h
fairmq/zeromq/FairMQMessageZMQ.cxx
fairmq/zeromq/FairMQMessageZMQ.h
fairmq/zeromq/FairMQTransportFactoryZMQ.cxx
fairmq/zeromq/FairMQTransportFactoryZMQ.h

- Use directly available `fTransportFactory` as the return value of `FairMQDevice::Transport()` instead of accessing the map.
- Fix namespaces in Transport.h
- Add conversion maps for string/enum version of transport labels.
- In Channel/Device the enum transport labels can be used instead of string.

Cleanup of transport management in device/channel

---

CMakeLists.txt
fairmq/Plugin.h
fairmq/PluginServices.h
fairmq/plugins/Control.cxx
fairmq/shmem/Monitor.cxx

These changes depend on FairLogger 1.2.0, that are submitted for FairSoft May18 release.

Control plugin: add ability to switch log levels interactively

---

fairmq/tools/Process.cxx

Discovered in aliBuild context. This bug is somehow masked when building against FairSoft.
---
Checklist:

Add missing header

---

fairmq/shmem/FairMQTransportFactorySHM.cxx
fairmq/zeromq/FairMQTransportFactoryZMQ.cxx

Transport has meaningful defaults if FairMQProgOptions is missing
Resolves #50.
---
Checklist:

Change missing options in transport from warning to debug

---

CMakeLists.txt
fairmq/CMakeLists.txt
fairmq/DeviceRunner.cxx
fairmq/DeviceRunner.h
fairmq/FairMQDevice.h
fairmq/FairMQStateMachine.cxx
fairmq/FairMQStateMachine.h
fairmq/Plugin.h
fairmq/PluginManager.cxx
fairmq/PluginManager.h
fairmq/PluginServices.cxx
fairmq/PluginServices.h
fairmq/devices/FairMQBenchmarkSampler.h
fairmq/plugins/Control.cxx
fairmq/plugins/Control.h
fairmq/runFairMQDevice.h
test/device/_multiple_devices.cxx
test/plugin_services/Fixture.h
test/plugin_services/_control.cxx
test/plugins/_plugin.cxx
test/plugins/_plugin_manager.cxx
test/plugins/_plugin_manager_prelink.cxx

- Run state handlers (e.g. InitTask(), Run(), ...) on the main thread. This solves some cases that require user code to be run on the main thread (@sawenzel). All the state handlers will be called in the same thread where the newly introduced `device.RunStateMachine()` method is called. It returns when state machine is done (after `END` event). To keep the device responsive when user code is run, state machine controller has to be run in an extra thread. This is a **breaking change** for anyone who does not use our control plugins and has a custom main function. The solution is to add a separate thread either for all the `ChangeState(...)` calls, or for `device.RunStateMachine()`. For an example fix you can see `test/device/_multiple_devices.cxx` inside this PR.
- Reduce number of action …

Run state handlers on the main thread [breaking change]

---

cmake/GTestHelper.cmake
fairmq/shmem/FairMQSocketSHM.cxx
fairmq/zeromq/FairMQSocketZMQ.cxx
test/CMakeLists.txt
test/device/_device_config.cxx
test/helper/devices/TestTransferTimeout.cxx

- Enable definitions propagation for tests.
- Use always-available transport for _device_config test (the test does not depend on any particular transport).
- Fix incorrect multipart transfer timeout handling for the ZeroMQ transport.
- Fix missing multipart transfer timeout handling for the shared memory transport.
- Include multipart transfer timeout testing in the unit tests.
---
Checklist:

Test timeout parts

---

examples/dds/README.md
fairmq/plugins/DDS/runDDSCommandUI.cxx

Before this the command UI could only target all devices at the same time.
Also, updated the DDS example readme.
Fixes #68.
---
Checklist:

 Allow DDS command UI to target parts of the topology

---

fairmq/plugins/Control.cxx

Fix race condition in the control plugin.
Resolves #83.
Tracing down the error in #83 reveals that `Control::WaitForNextState()` misses the condition variable notification that is sent by the state change handler. Adding a timeout forces him to check the condition even without notification.
However further investigation is necessary as to why the problem appears in the first place - the locks in the aforementioned methods are setup to prevent this from happening.
---
Checklist:

Fix race condition in the control plugin

---

cmake/FairMQLib.cmake
fairmq/CMakeLists.txt

1. Support CMake variable [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html) (triggered by #89).
2. Fix an ODR violation in the unity build regarding posix signal handling. @rbx Could this be related to the issue with the missed `SIGINT`? Strangely neither of the CI builds generate an error here, only get it with GCC 8.
---
Checklist:

Support static builds

---

fairmq/DeviceRunner.cxx
fairmq/FairMQDevice.cxx
fairmq/FairMQDevice.h
fairmq/FairMQStateMachine.cxx
fairmq/PluginServices.h
fairmq/devices/FairMQBenchmarkSampler.cxx
fairmq/plugins/Control.cxx
fairmq/plugins/Control.h
fairmq/runFairMQDevice.h
fairmq/tools/Process.cxx
fairmq/tools/Process.h
test/CMakeLists.txt
test/device/_exceptions.cxx
test/helper/devices/TestExceptions.cxx
test/helper/runTestDevice.cxx

Proposal to solve #95.
@rbx It is not yet working as expected, when I throw in `Run()`:
```
[21:25:27][INFO] DEVICE: Running...
[21:25:27][STATE] Entering ERROR state
terminate called without an active exception
[1]    30405 abort (core dumped)  test/testhelper_runTestDevice --id waitfor_ --control static
```
as opposed to when I throw in `InitTask()` (this behaviour is what I want):
```
[21:24:48][STATE] Entering INITIALIZING_TASK state
[21:24:48][STATE] Entering ERROR state
[21:24:48][DEBUG] Shutting down Plugin Manager
[21:24:48][DEBUG] Unloaded plugin: 'control', version '1.3.3', maintainer 'FairRootGroup <fairroot@gsi.de>', homepage 'https://github.com/FairRootGroup/FairRoot'
[21:24:48][DEBUG] Shutting down Plugin Services
[21:24:48][DEBUG] Destructing device waitfor_ …
```

Resolve hanging process in case of uncaught exception

---

FairMQTest.cmake
cmake/FairMQLib.cmake

Fixes bug when setting build type in CI jobs.
---
Checklist:

Pick correct build type in CI

---

fairmq/FairMQChannel.cxx
fairmq/FairMQChannel.h
fairmq/FairMQDevice.h
fairmq/FairMQSocket.h
fairmq/nanomsg/FairMQSocketNN.cxx
fairmq/nanomsg/FairMQSocketNN.h
fairmq/shmem/FairMQSocketSHM.cxx
fairmq/shmem/FairMQSocketSHM.h
fairmq/zeromq/FairMQSocketZMQ.cxx
fairmq/zeromq/FairMQSocketZMQ.h
test/helper/devices/TestTransferTimeout.h

Deprecate Send-/ReceiveAsync, use timeout variant instead.
The naming of these methods is confusing and the logic can be expressed via the timeout value of 0.
---
Checklist:

Deprecate Send-/ReceiveAsync, use timeout variant instead

---

fairmq/FairMQChannel.cxx
fairmq/FairMQChannel.h
fairmq/FairMQDevice.cxx
fairmq/FairMQDevice.h
fairmq/options/FairMQProgOptions.cxx

- Add missing channel update handlers in FairMQProgOptions.
- Use exceptions consistently for fatal errors in device/channel that will be caught by StateMachine::ProcessWork and lead to error state.
- Solve issue where device goes into ready state if it encounters misconfigured channel in the Run (solves #109).
- deprecate WaitForInitialValidation() - it is not doing anything meaningful since the new control/config plugins.
- Add a warning at the end of initialization if no channels have been created.
---
Checklist:

Use exceptions consistently & other fixes

---

fairmq/FairMQDevice.h
fairmq/FairMQStateMachine.cxx
fairmq/PluginServices.h
fairmq/options/FairMQProgOptions.cxx
fairmq/options/FairMQProgOptions.h

This also fixes a bug, that prevented the usage of custom types with the
plugin config API.
Example:
```cpp
// in DeviceState::Idle
vector<string> channels;
channels.push_back("name=asdf,method=bind,type=pull");
SetProperty("channel-config", channels);
```
This is a workaround for channel creation from plugins only. One should still configure the channels as usual in `DeviceState::InitializingDevice` via `SetProperty("chans.asdf.0.address", "tcp://...");` (In FairMQ 1.4 channels will be implicitely created, if a plugin sets properties on it).
---
Checklist:

Allow plugins to create channels

---

CONTRIBUTORS
fairmq/options/FairMQProgOptions.cxx
fairmq/tools/Unique.cxx

This fixes an issue with `boost::uuids::random_generator` which only seems to happen on some systems. I've managed to reproduce it in a VM, with CC7.3 (which ships Linux 3.10). As it turns out, the kernel in question does not have `getrandom`, but `boost::uuids::random_generator` tries to use it anyway and fails miserably, throwing a `boost::uuids::entropy_error`.
Ultimately, this results in `[ERROR] Uncaught exception reached the top of main: getrandom` and it happens immediately on startup (tested with the fairmq-ex-1-n-1 example).
The safe and compatible option is to `#define BOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX` so Boost uses plain `/dev/*random`.

Avoid boost::uuids::entropy_error on some systems

---

fairmq/FairMQChannel.cxx
fairmq/FairMQChannel.h
fairmq/FairMQDevice.cxx
fairmq/FairMQDevice.h
fairmq/FairMQSocket.h
fairmq/nanomsg/FairMQSocketNN.cxx
fairmq/nanomsg/FairMQSocketNN.h
fairmq/ofi/Socket.cxx
fairmq/ofi/Socket.h
fairmq/options/FairMQParser.cxx
fairmq/options/FairMQProgOptions.cxx
fairmq/options/FairMQProgOptions.h
fairmq/options/FairMQSuboptParser.h
fairmq/shmem/FairMQSocketSHM.cxx
fairmq/shmem/FairMQSocketSHM.h
fairmq/tools/Process.cxx
fairmq/zeromq/FairMQSocketZMQ.cxx
fairmq/zeromq/FairMQSocketZMQ.h
test/channel/_channel.cxx
test/protocols/_push_pull_multipart.cxx

- Move BindEndpoint/ConnectEndpoint to FairMQChannel (#101).
- Use delegating constructors in FairMQChannel.
- Allow setting port range for dynamic binding per-channel, instead of per-device.
- Make dynamic binding optional (on by default).
- Formatting.
- Move short methods from source file to header file.
- Remove `PrintChannel()` from FairMQDevice, it is unused and outdated, if needed it can become a method of FairMQChannel.
- Change return type of `Connect()` in the transport interface - from void to bool.
---
Checklist:

Move Bind/Connect from FairMQDevice to FairMQChannel

---

fairmq/FairMQMessage.h
fairmq/nanomsg/FairMQMessageNN.cxx
fairmq/nanomsg/FairMQMessageNN.h
fairmq/nanomsg/FairMQSocketNN.cxx
fairmq/ofi/Message.cxx
fairmq/ofi/Message.h
fairmq/shmem/FairMQMessageSHM.cxx
fairmq/shmem/FairMQMessageSHM.h
fairmq/shmem/FairMQSocketSHM.cxx
fairmq/zeromq/FairMQMessageZMQ.cxx
fairmq/zeromq/FairMQMessageZMQ.h
fairmq/zeromq/FairMQSocketZMQ.cxx
test/CMakeLists.txt
test/message/_message.cxx

- Fix bug in shmem CloseMessage (occurs when Rebuild is used).
- Add test for FairMQMessage::Rebuild.
- Remove previously deprecated Copy method (since 1 year).
---
Checklist:

Add test for FairMQMessage::Rebuild

---

fairmq/FairMQTransportFactory.h
test/memory_resources/_memory_resources.cxx

reduces boilerplate in many places, logic is clear: factory can be treated like a memory resource where appropriate.

Allow implicit conversion factory->resource

---

CMakeLists.txt
fairmq/CMakeLists.txt

Needed to support Boost 1.69, which dropped the signals v1 library. Anyways, we are not using it any more, so we can just remove the dependency.

Remove obsolete dependency to boost signals v1

---

fairmq/FairMQChannel.h
fairmq/FairMQDevice.h

`FairMQDevice::NewUnmanagedRegion(...)` did not allow passing a callback as `FairMQDevice::NewUnmanagedRegionFor(...)` does. This fixes it.
Also add wrapper method in FairMQChannel, similar to other factory methods.
---
Checklist:

Allow creating region with a callback with default transport

---

test/device/TestReceiver.h
test/device/TestSender.h
test/device/_error_state.cxx
test/device/_exceptions.cxx
test/device/_signals.cxx

The affected tests have independent shutdown conditions that race with the controller inputs.
---
Checklist:

Remove controller input for several tests

---

examples/multipart/CMakeLists.txt
examples/multipart/Sampler.cxx
fairmq/FairMQParts.h

This introduces a little helper to create a FairMQParts object in place from a
variable list of arguments. As a side effect also AddParts is extended to support
more than one FairMQMessagePtr.
An example use case is the initialization of a FairMQParts member in a class constructor.

Extending FairMQParts by a constructor taking list of FairMQMessagePtr

---

fairmq/FairMQDevice.h
fairmq/plugins/Control.cxx
fairmq/tools/Process.cxx
fairmq/tools/Process.h
test/device/_waitfor.cxx
test/helper/devices/TestErrorState.h
test/helper/devices/TestExceptions.h
test/helper/devices/TestWaitFor.h

- fair::mq::tools::execute - add output helper to avoid duplicate code.
- fair::mq::tools::execute - support sending of a signal to the process.
- tests: Use process tools in WaitFor test.
- Add more checks in WaitFor test.
- Reduce polling rate in Control::InteractiveMode() from 500 to 100 ms (accelerate some tests).
- Fix bug in WaitFor with wrong return value (didn't match the docs).
---
Checklist:

Extend process tools

---

fairmq/plugins/Control.cxx

The control plugin assumed transition to init is always successful.
---
Checklist:

Handle invalid transition to init in the control plugin

---

fairmq/shmem/FairMQMessageSHM.cxx
fairmq/shmem/Manager.cxx
fairmq/shmem/Manager.h
fairmq/shmem/Region.cxx
fairmq/shmem/Region.h
fairmq/tools/CppSTL.h

This is performance optimization for releasing of freed SHM messages allocated from a UnmanagedRegion. The change introduce another thread per Region object used to transmit freed region block information in batches. This reduces contention on the IPC synch objects and leads to lower CPU utilization in both, originating and freeing processes.
Also: refactor the `Manager` class since `Region` is no longer copyable or moveable (mutex).
---
Checklist:

Bunch Region Acks when sending over IPC queue

---

examples/region/Sampler.cxx
examples/region/Sink.cxx
fairmq/FairMQChannel.h
fairmq/FairMQDevice.h
fairmq/FairMQTransportFactory.h
fairmq/nanomsg/FairMQTransportFactoryNN.cxx
fairmq/nanomsg/FairMQTransportFactoryNN.h
fairmq/nanomsg/FairMQUnmanagedRegionNN.cxx
fairmq/nanomsg/FairMQUnmanagedRegionNN.h
fairmq/ofi/TransportFactory.cxx
fairmq/ofi/TransportFactory.h
fairmq/shmem/Common.h
fairmq/shmem/FairMQMessageSHM.cxx
fairmq/shmem/FairMQSocketSHM.cxx
fairmq/shmem/FairMQTransportFactorySHM.cxx
fairmq/shmem/FairMQTransportFactorySHM.h
fairmq/shmem/FairMQUnmanagedRegionSHM.cxx
fairmq/shmem/FairMQUnmanagedRegionSHM.h
fairmq/shmem/Manager.cxx
fairmq/shmem/Manager.h
fairmq/shmem/Monitor.cxx
fairmq/shmem/Monitor.h
fairmq/shmem/Region.cxx
fairmq/shmem/Region.h
fairmq/shmem/runMonitor.cxx
fairmq/zeromq/FairMQTransportFactoryZMQ.cxx
fairmq/zeromq/FairMQTransportFactoryZMQ.h
fairmq/zeromq/FairMQUnmanagedRegionZMQ.cxx
fairmq/zeromq/FairMQUnmanagedRegionZMQ.h

- Support huge pages via path to hugetlbfs mount and/or flags to mmap. Adds optional path/flags arguments to interface of region creation.
- Store region info in shared memory with paths and flags,
- Shmem refactoring: move device counter and monitor launcher from factory to manager class,
- Formatting...
---
Checklist:

Shmem region: support huge pages via path to hugetlbfs mount

---

fairmq/FairMQDevice.h

Fix `WaitForState(const string& stateName)` to actually call `WaitForState(fair::mq::State state)`.
---
Checklist:

Fix WaitForState(string stateName)

---

examples/dds/CMakeLists.txt
examples/dds/ex-dds-topology-infinite.xml
examples/dds/fairmq-start-ex-dds.sh.in
fairmq/plugins/Control.cxx
fairmq/plugins/DDS/DDS.cxx
fairmq/plugins/DDS/DDS.h
fairmq/plugins/DDS/runDDSCommandUI.cxx
fairmq/sdk/Topology.cxx
fairmq/sdk/Topology.h
test/sdk/Fixtures.h
test/sdk/_topology.cxx
test/sdk/test_topo.xml

Up to now the DDS plugin only support a mix of internal and external control. With `--control external` (alias for `dynamic` and `interactive`) it does not attempt to do any control action internally. Moreover, `external` is the default value now.
The `fairmq-dds-command-ui -n` option is only a temporary solution and should be improved on further (#188).
Resolves #184.

DDS plugin: Add --control external support

---

CMakeLists.txt

In `1.4` we use functionality only available since Boost `1.66` but we missed bumping the version requirement.

FairMQ: Require Boost 1.66

---

examples/dds/CMakeLists.txt
fairmq/sdk/Topology.cxx
fairmq/sdk/Topology.h

`fair::mq::Topology`:
- Use `DDSTask` type in all places.
- Remove unused member `fStateChangesSubscriptions`.
- Execute test for DDS example only if DDS was found.
---
Checklist:

Topology: Use DDSTask type, remove unused member

---

FairMQTest.cmake
Jenkinsfile
Jenkinsfile.nightly
fairmq/plugins/Control.cxx
fairmq/sdk/CMakeLists.txt
fairmq/sdk/DDSCollection.h
fairmq/sdk/DDSSession.cxx
fairmq/sdk/DDSTask.h
fairmq/sdk/DDSTopology.cxx
fairmq/sdk/DDSTopology.h
fairmq/sdk/Topology.h
test/sdk/Fixtures.h
test/sdk/_topology.cxx
test/sdk/test_topo.xml

Add a simple GroupByCollectionId implementation and related (or less related) changes:
- sdk: Add `DDSCollection` class
- sdk: Add `DDSTopology::GetCollections()` and extend `DDSTask`
- Add collections to test topology
- Add `sdk::GroupByCollectionId(TopologyState)`
- Add test for `sdk::GroupByCollectionId(TopologyState)`
- Handle InitializingDevice in the ShutdownSequence 
`sdk::TopologyState` is now a `std::vector<DeviceStatus>`, and `DeviceStatus` contains task id and collection id.
For #204.

Add sdk::GroupByCollectionId(TopologyState)

---

Jenkinsfile
Jenkinsfile.nightly
examples/dds/ex-dds-topology-infinite.xml
examples/dds/ex-dds-topology.xml
fairmq/FairMQDevice.cxx
fairmq/plugins/DDS/DDS.cxx
fairmq/sdk/DDSTopology.h
fairmq/sdk/Topology.h
test/sdk/test_topo.xml

- Slight optimization in the container handling in the SDK::Topology - simplify the map content and keep the final vector around from the beginning to avoid copy at the end.
- breaking change in the topology xml files: properties that are used for channel communication are now prefixed with `fmqchan_<property_name>`.

Sdk tweaks

---

fairmq/sdk/commands/CMakeLists.txt
fairmq/sdk/commands/Commands.cxx
fairmq/sdk/commands/Commands.h
fairmq/sdk/commands/CommandsFormatDef.h.in
test/commands/_commands.cxx

Allow for the commands to be optionally serialized as JSON instead of binary flatbuffers.
This feature is provided by the flatbuffers implementation.
For this feature flatbuffers needs to see the definitions file at run time (`CommandsFormat.fbs`). To avoid locating and loading this file, I store it to a static string during the build.
Also fix some missing consts.

Commands: support JSON in addition to binary

---

fairmq/shmem/Common.h
fairmq/shmem/FairMQTransportFactorySHM.cxx
fairmq/shmem/Manager.cxx
fairmq/shmem/Manager.h
fairmq/shmem/Monitor.cxx
fairmq/shmem/Monitor.h
fairmq/shmem/README.md
fairmq/shmem/runMonitor.cxx

- Start monitor before creating the segments.
- Allow running the monitor in view-only mode (with `--view`) that will ignore that presence of any other active monitor and will only allow viewing the segment info without modifying it.
- Some refactoring.

Shm monitor: fix startup race and enable view-only mode

---

fairmq/plugins/DDS/DDS.cxx
fairmq/plugins/DDS/DDS.h

Part of the shutdown handling code was accidentally removed with the introduction of commands format.
Also removing StateQueue in the plugin that is unused.

Fix regression in the DDS plugin shutdown handling

---

fairmq/shmem/FairMQMessageSHM.cxx
fairmq/shmem/FairMQMessageSHM.h
fairmq/shmem/FairMQSocketSHM.cxx

Fixes an issue that received multipart messages over shmem did not have their meta data fully initialized, which lead to problems when re-sending them.
I will add a test for this case in a separate PR.

shmem: properly initialize received multipart messages

---

CMakeLists.txt
fairmq/CMakeLists.txt
fairmq/DeviceRunner.cxx
fairmq/Plugin.cxx
fairmq/Plugin.h
fairmq/plugins/PMIx/CMakeLists.txt
fairmq/plugins/PMIx/PMIx.hpp
fairmq/plugins/PMIx/PMIxCommands.h
fairmq/plugins/PMIx/PMIxPlugin.cxx
fairmq/plugins/PMIx/PMIxPlugin.h
fairmq/plugins/PMIx/runPMIxCommandUI.cxx

- Add a wrapper for PMIx command APIs (register/deregister/notify)
- Update PMIx plugin to use the command interface and replace `fence()`s with control via commander.
- Add `fairmq-pmix-command-ui` that uses the command API to control the devices.
This is what I used to test/run this:
server:
```
prrte/bin/prte
```
app:
```
prrte/bin/prun -v -np 1 fairmq-pmix-command-ui -n 2 : -np 1 fairmq-bsampler -P pmix --channel-config name=data,type=push,method=bind --max-iterations 10 : -np 1 fairmq-sink -P pmix --channel-config name=data,type=pull,method=connect --max-iterations 10
```

PMIx: Update wrapper, add commands to plugin, add command ui

---

fairmq/FairMQDevice.cxx
fairmq/tools/Network.cxx
fairmq/tools/Network.h

Fixes #230.
detection will first try `/proc/net/route` then `ip route | grep default | cut -d " " -f 5 | head -n 1` and if both fail we will bind on `tcp://*:1`.

Detect network interface of the default route without use of ip

---

fairmq/sdk/Topology.h
fairmq/shmem/Socket.cxx
test/sdk/_topology.cxx

Refactors StateChangeOp to allow concurrent invocations and adds a path parameter to the call that allows to target subsets of the topology.

SDK: Refactor StateChangeOp and add path parameter

---

fairmq/plugins/DDS/DDS.cxx
fairmq/plugins/DDS/DDS.h

Provide descriptive error message when DDS plugin receives an update for a non-existing channel.
Refactor parts of the DDS plugin code for better readability.
Resolves #206.

DDS plugin: Improve error messages

---

examples/README.md
examples/qc/CMakeLists.txt
examples/qc/README.md
examples/qc/ex-qc-topology.xml
examples/qc/fairmq-start-ex-qc.sh.in
examples/qc/runQCDispatcher.cxx
examples/qc/runQCTask.cxx
fairmq/plugins/DDS/runDDSCommandUI.cxx
fairmq/sdk/Topology.h

- SDK: refactor subscriptions to allow reuse.
- DDSCommandUI: include path argument in ChangeState.
- QC example: rename QC devices, more granular state control in the script.

QC example update

---

fairmq/plugins/DDS/DDS.cxx
fairmq/plugins/PMIx/PMIxPlugin.cxx
fairmq/sdk/Topology.h
fairmq/sdk/commands/Commands.cxx
fairmq/sdk/commands/Commands.h
fairmq/sdk/commands/CommandsFormat.fbs
test/commands/_commands.cxx

- Replace the `sleep()` in the destructor of `sdk::Topology` with a proper tracking of state unsubscription commands, to make sure all of them arrived at each task. Also set a task as unsubscribed if it is exiting, since it won't respond to an unsubscription command anymore.
- Add task ID to state subscription commands.
- Some minor refactoring of the command handling.
The `initialized` member of `sdk::DeviceStatus` is renamed to `subscribed_to_state_changes`. The subscription status conveys similar information (and more) and is now used to implement first point.

SDK: track (un-)subscriptions

---

fairmq/plugins/DDS/DDS.cxx
fairmq/plugins/DDS/DDS.h
fairmq/plugins/PMIx/runPMIxCommandUI.cxx
fairmq/sdk/Topology.h
fairmq/sdk/commands/Commands.cxx
fairmq/sdk/commands/Commands.h
fairmq/sdk/commands/CommandsFormat.fbs
test/commands/_commands.cxx

Solves #190.
When subscribed to state changes SDK will send heartbeats in regular intervals (by default every 60 seconds, configurable) to the devices.
Plugin that receives the heartbeats, will check (lazily, before attempting to send a changed state command) if the last heartbeat from this subscriber arrived less than 3 times the declared interval ago. If so, it will send the command, and if not it will assume subscriber is no longer there and remove it.

Sdk subscription heartbeats

---

fairmq/FairMQTransportFactory.h
fairmq/FairMQUnmanagedRegion.h
fairmq/nanomsg/FairMQTransportFactoryNN.cxx
fairmq/nanomsg/FairMQTransportFactoryNN.h
fairmq/nanomsg/FairMQUnmanagedRegionNN.cxx
fairmq/nanomsg/FairMQUnmanagedRegionNN.h
fairmq/ofi/TransportFactory.cxx
fairmq/ofi/TransportFactory.h
fairmq/shmem/Manager.cxx
fairmq/shmem/Manager.h
fairmq/shmem/TransportFactory.cxx
fairmq/shmem/TransportFactory.h
fairmq/shmem/UnmanagedRegion.h
fairmq/zeromq/FairMQTransportFactoryZMQ.cxx
fairmq/zeromq/FairMQTransportFactoryZMQ.h
fairmq/zeromq/FairMQUnmanagedRegionZMQ.cxx
fairmq/zeromq/FairMQUnmanagedRegionZMQ.h
test/CMakeLists.txt
test/region/_region.cxx

- Implement subscriptions for region events and `GetRegionInfo()` for ZeroMQ transport. If subscribed, ZeroMQ transport will first call a region event with `FairMQRegionEvent::local_only` to notify that callbacks are only called for regions created by this transport.
- Add `bool FairMQTransportFactory::SubscribedToRegionEvents()` that returns true if a subscription is already active (currently only a single subscription at a time is allowed).
- Add `uint64_t FairMQUnmanagedRegion::GetId()` that returns the id of the region. This id corresponds to the one returned in the region info events (`FairMQRegionInfo::id`).

Implement region events for zmq

---

CMakeLists.txt

Can be overridden by -DUSE_EXTERNAL_GTEST=ON.
Related to FairRootGroup/FairSoft#250.

Do not search external GTest by default

---

fairmq/plugins/Control.cxx

A double SIGTERM, or even worse a SIGINT + SIGTERM combination should
not result in an abort, given such a signal really means "die whenever
you want" and can only be generated programmatically. If one wants the
child to die programmatically, they should use SIGKILL.
On the other hand that bashing ctrl-c (i.e. SIGINT) multiple times
on the keyboard really means abort.

Do not handle double SIGTERM as abort

---

fairmq/FairMQMessage.h
fairmq/FairMQTransportFactory.h
fairmq/ofi/Message.cxx
fairmq/ofi/Message.h
fairmq/ofi/TransportFactory.cxx
fairmq/ofi/TransportFactory.h
fairmq/shmem/Message.h
fairmq/shmem/TransportFactory.h
fairmq/zeromq/Message.h
fairmq/zeromq/TransportFactory.h
test/message/_message.cxx

Adds the alignment interface, and implementation for shmem send case. Other cases (shm receive check, zmq send/recv) ignore the argument for now.

Alignment part I - Interface and shmem send

---

fairmq/plugins/Control.cxx

#266 exposed the fact that FairMQ does not really handle SIGTERM. This should make sure processes actually try to quit when received.

Initiate termination process on SIGTERM as well

---

fairmq/ProgOptions.cxx

Explicitly list (and override the default) the program option styles. Disable `allow_guessing`.

Adjust program options style to disallow guessing

---

fairmq/MemoryResources.cxx

`fair::mq::ChannelResource`: propagate the alignment parameter to the message constructor.

MemoryResource: propagate alignment

---

.gitmodules
CMakeLists.txt
COPYRIGHT
cmake/FairMQLib.cmake
cmake/FindPicoSHA2.cmake
fairmq/CMakeLists.txt
fairmq/shmem/Common.h
fairmq/zeromq/Message.h
test/message/_message.cxx

- Add bundled dependency on PicoSHA2.
- Update hash algorithm that generates hash for shmem id from boost::hash to SHA-2. Former can result in collisions on MacOS, primarily because we have to truncate the hash value to accommodate for the name length limit.
Also:
- Update ZeroMQ transport's GetData() to return `nullptr` for empty messages.

Update algorithm to generate hash for shmem id 

---

fairmq/FairMQChannel.cxx
fairmq/devices/FairMQBenchmarkSampler.h
fairmq/shmem/Manager.h
fairmq/shmem/Message.h

- When autobind is enabled, do not try to find a new port for non-TCP protocols.
- Shm: throw if requested message size exceeds total segment size
- BenchmarkSampler: remove unused variable.
- Shm: when opening segment created by another device, report the actual size of the opened segment, and not the one configured on this device.

Do not attemp to find random port for non-TCP protocols

---

examples/qc/fairmq-start-ex-qc.sh.in
fairmq/plugins/DDS/runDDSCommandUI.cxx
fairmq/sdk/Topology.h

- QC example: Fix the path argument that results in no tasks getting selected.
- SDK: warn if an operation is initiated on an empty set of tasks.

Fix topology path in QC example

---

fairmq/FairMQSocket.h
fairmq/shmem/Socket.h
fairmq/zeromq/Socket.h

This exposes to the user the ZMQ_EVENTS API, so that we can reliably integrate FairMQ with third party event loops like libuv.
While I appreciate this exposes some internal details of the FairMQSocket, I see no easy solution when introducing multithreading inside a given device as the lack of knowledge about the event types leads to 100% CPU utilisation on the event loop thread (which handles the interaction with fairmq). The single threaded implementation done so far is immune to the issue because the payload itself acts a mitigator.
As for the ZMQ_FD case, this is not expected to a stable API and I am happy to adapt to a better solution which provides the same / similar functionality, when available.

Add API to extract ZMQ_EVENTS from socket backend

---

fairmq/States.cxx
fairmq/States.h
fairmq/sdk/Error.h
fairmq/sdk/Topology.h
fairmq/sdk/commands/Commands.cxx
fairmq/sdk/commands/CommandsFormat.fbs
test/sdk/_topology.cxx

`fair::mq::sdk::AggregateState` no longer throws exception on a mixed state, but returns `fair::mq::DeviceState::Mixed` instead.
Solves #286 @AndreyLebedev.

Add Undefined and Mixed states for use in SDK

---

fairmq/sdk/Topology.h
test/sdk/_topology.cxx

Solves #291.
In principle I would prefer to have all state/transition strings to be TitleCase, like the state names. However I'm not sure if anyone already depends on uppercase ones. `GetState`, `GetTransition` and `GetAggregateTopologyState` can support both, but conversion from type to string could only be either/or.

Add helpers for AggregatedTopologyState

---

fairmq/devices/FairMQBenchmarkSampler.h
fairmq/run/runBenchmarkSampler.cxx
fairmq/shmem/Manager.h
fairmq/shmem/Message.h
fairmq/shmem/Monitor.cxx
fairmq/shmem/Monitor.h
fairmq/shmem/runMonitor.cxx

- Error handling for mlock.
- BenchmarkSampler: add alignment parameter.
- shm MessageBadAlloc: report amount of available memory.
- shmmonitor: add output with -v (non-interactive).

Shm options & helpers

---

fairmq/shmem/Manager.h

- Use relaxed memory ordering to keep the global atomic message counter. Final check uses acquire ordering for read serialization
- Move RateLimit constructor and call to clock::now() out of the fast path. 2x faster message allocation
---
Checklist:

Performance optimizations

---

fairmq/shmem/Message.h

Avoid unconditional call to now() when allocating message. As discussed in #296.

Avoid unconditional call to now() when allocating message

---

fairmq/shmem/Poller.h
fairmq/shmem/Socket.h
fairmq/shmem/TransportFactory.h
fairmq/zeromq/Context.h
fairmq/zeromq/Poller.h
fairmq/zeromq/Socket.h

Retry when a blocking ZeroMQ call returns `EINTR`.
The relevant signals are picked up by the controller plugin and propagated in their own way to unblock the calls.

Retry on EINTR in blocking zmq calls

---

fairmq/plugins/DDS/DDS.cxx
fairmq/sdk/Topology.h
fairmq/sdk/commands/Commands.cxx
fairmq/sdk/commands/Commands.h
fairmq/sdk/commands/CommandsFormat.fbs
fairmq/sdk/runDDSCommandUI.cxx
test/commands/_commands.cxx

- Avoid these types of messages:
```
[ERROR] STOP transition failed for main/Sampler_0
[ERROR] STOP transition failed for main/Sink_0
```
when the expected state is already reached. Only output the error if they don't match, otherwise only debug message.
- Include current_state in TransitionStatus command for better debugging.
- `fairmq-dds-command-ui`: output an error when ChangeState fails.

Improve error reporting in SDK/fairmq-dds-command-ui

---

Jenkinsfile
fairmq/FairMQChannel.h
fairmq/FairMQDevice.h
fairmq/FairMQSocket.h
fairmq/ofi/Socket.cxx
fairmq/sdk/Topology.h
fairmq/shmem/Socket.h
fairmq/zeromq/Socket.h
test/CMakeLists.txt
test/helper/devices/TestTransferTimeout.h
test/sdk/_topology.cxx
test/transport/_transfer_timeout.cxx

Currently, a `Stop` transition during the `Running` state will interrupt the transfers. Blocking transfer calls (`Send`/`Receive`) will return `-2` (timeout). If another transfer is attempted before transitioning to Ready state, the behaviour of zmq/shmem transport is inconsistent. Another call to zmq transfer will attempt to complete the transfer with a certain timeout, while shmem transfer will not attempt any transfer and immediately return `-2` again.
There are scenarios when doing another transfer can be useful. One such scenario is to send an `end-of-stream` message when `Stop` happens. See some discussion of such a use case here: https://alice.its.cern.ch/jira/browse/O2-1499
This PR:
- gives names to different return values of the transfer methods: `TransferResult::error`, …

Adjust transfer methods behaviour when interrupted

---

fairmq/plugins/PMIx/PMIxPlugin.cxx
test/memory_resources/_memory_resources.cxx

- Avoid default session id in shmem tests. Should fix these types of failures: https://cdash.gsi.de/testDetails.php?test=7170379&build=246945. Also refactored the test a bit to avoid global objects and capitalize the type names.
- Update command format in PMIx plugin. Fixes #307.

Fix a couple of issues

---

fairmq/FairMQChannel.h

Fixes #298.
`std::vector` wants FairMQChannel to be movable. When the move ctor is explicitly deleted, it fails, at least on xcode 12, but also on linux clang 10.0.1: https://godbolt.org/z/z3rY6n
Removing the `FairMQChannel(FairMQChannel&&) = delete` from the code causes the vector's move attempt to fall back to copy, which is fine for this case.

Workaround Cpp17MoveInsertable issue on xcode 12

---

fairmq/ofi/Socket.cxx

Update return types in ofi::Socket.
alisw/alidist/pull/2494.
@dennisklein we need to include ofi transport in some of the test environments.

Update return types in ofi::Socket

---

CONTRIBUTORS
cmake/FindPMIx.cmake

Debian's libpmix-dev package installs everything below /usr/lib/ARCH-TRIPLET/pmix2.
For some reasoning behind this, see: https://bugs.debian.org/882033
CMake does not search there by default, so help it.
Checklist:

Improve PMIx Package Finding on Debian

---

fairmq/sdk/DDSSession.cxx
fairmq/sdk/Topology.h
test/sdk/Fixtures.h
test/sdk/_topology.cxx

It should be possible to construct and use concurrently `sdk::DDSSession` and `sdk::Topology`. The limitations on the DDS side that required this should no longer be there according to @AnarManafov & @AndreyLebedev (can you specify the DDS version since which this is the case? So that we bump the minimum requirement).

SDK: Remove instance limit from DDSSession

---

fairmq/FairMQChannel.h
fairmq/FairMQDevice.h
fairmq/FairMQSocket.h
fairmq/ofi/Socket.cxx
fairmq/ofi/Socket.h
fairmq/shmem/Socket.h
fairmq/zeromq/Socket.h

Due to historical reasons (ZeroMQ transfer methods return int) all single-message transfer methods return `int`. While this is fine for ZeroMQ, other transports are capable of transferring larger data sizes in a single message. This PR changes all transfer methods return types to int64_t.
Triggered by AliceO2Group/AliceO2/pull/4804 (although not the cause for any trouble in that case).

Let single message methods also return int64_t

---

fairmq/shmem/Manager.h

If mlocking/zeroing of the segment is done outside of the shmem lock, it is possible that region event consumers may be notified before segment is locked/zeroed, which is undesirable in some cases. These changes fix it by doing mlock/zeroing under the same shmem lock.

shm: do mlock/zeroing under shmem lock

---

fairmq/shmem/Monitor.cxx
fairmq/shmem/runMonitor.cxx

With this change the `fairmq-shmmonitor` (when run with `-v` (view only)) will output the segment contents and exit immediately.
To get continuous output, use `-i` (interactive).
The output format is same for both.
@sawenzel This does what you requested.
@davidrohr FYI: with this you might have to modify your options if you have been using `-v` only, but want continuous output.

shmmonitor: non-interactive mode checks and quits

---

fairmq/SuboptParser.cxx
test/CMakeLists.txt
test/properties/_suboptparser.cxx

The current syntax is ambiguous because it treats assignments
(like address=127.0.0.1) and selectors (name=my-channel) using
the symbol equal `"`.
This allows:
my-channel:address=127.0.0.1
as alternative syntax, which clearly separates the role of my-channel
from the associated properties.
Describe your proposal.
Mention any issue this PR resolves or is related to.
---
Checklist:
* [x ] Rebased against `dev` branch
* [ x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [ x] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

Provide a better syntax for --channel-config

---

fairmq/shmem/Message.h
test/message/_message.cxx

SetUsedSize with shmem can fail due to boost alignment requirements. 
Handle this gracefully: either leave the old size allocated if the difference is below 1MB, or reallocate completely if greater (latter case should not happen in practice, but cover it just in case it does..).

shm: handle shrink failure gracefully

---

fairmq/shmem/Common.h
fairmq/shmem/Manager.h
fairmq/shmem/Monitor.cxx
fairmq/shmem/Monitor.h
fairmq/shmem/README.md
fairmq/shmem/TransportFactory.h
fairmq/shmem/runMonitor.cxx
fairmq/tools/Strings.h

- shmmonitor: update docs.
- shmmonitor: add --list-all.
- Add tools: StrStartsWith, StrEndsWith.
- shm: reduce delay between monitor daemon launch & HBs.
- shmmonitor: daemon output to file if FAIRMQ_SHMMONITOR_VERBOSE is true.
- shmmonitor: use fairlogger.
- shmmonitor: refactor to separate monitoring from output.
- shmmonitor: optimize startup to avoid repeated start.
- shmmonitor: add session name and creator id to the output.
- shmmonitor: enable read only access.
- shmmonitor: distinguish daemon from monitor mode (orthogonal).
- shmmonitor: allow getting shmids based on session/userid.

Shmmonitor updates

---

fairmq/FairMQSocket.h
fairmq/shmem/Socket.h
fairmq/zeromq/Socket.h

If the call is interrupted by a signal, this will throw, which we clearly do not want. Simplifying the API to let the user decide what to do on error is probably the best option.
See also https://alice.its.cern.ch/jira/browse/O2-2257.
---

Improve Events API

---

examples/region/Sampler.cxx
examples/region/Sink.cxx
examples/region/fairmq-start-ex-region.sh.in
examples/region/test-ex-region.sh.in
fairmq/FairMQTransportFactory.h
fairmq/FairMQUnmanagedRegion.h
fairmq/Transports.h
fairmq/ofi/Socket.h
fairmq/ofi/TransportFactory.cxx
fairmq/shmem/Manager.h
fairmq/shmem/Message.h
fairmq/shmem/Monitor.cxx
fairmq/shmem/README.md
fairmq/shmem/Region.h
fairmq/shmem/TransportFactory.h
fairmq/shmem/UnmanagedRegion.h
fairmq/shmem/runMonitor.cxx
fairmq/zeromq/Message.h
fairmq/zeromq/TransportFactory.h
fairmq/zeromq/UnmanagedRegion.h
test/device/_error_state.cxx

- Shm: check result of region acquisition.
- Configurable transport for region example script.
- Add operator<< for fair::mq::Transport.
- Add GetType() to UnmanagedRegion.
- Check transport type of msg and corresponding region.
- Shm: eliminate race/deadlock in region subscriptions.
- Shmmonitor: add severity setting.
- Update docs.
- Region example: fix msg counter.
- Shm: reduce shm contention when dealing with ack queues.
- Add mlock/zero options to unmanaged region.
- ofi: fix Events() signature.

shmem fixes and improvements, misc

---

fairmq/shmem/Manager.h
fairmq/shmem/Message.h
fairmq/shmem/Region.h

Race condition was introduced that could lead to a crash when messages are destroyed from multiple threads.

shm: revert some changes from c85d6e0 that introduced a race

---

fairmq/ProgOptions.cxx
fairmq/ProgOptions.h

Access was not protected in some cases.
Fixes #385.

Protect access to options container

---

examples/copypush/sampler.cxx
examples/n-m/sender.cxx
examples/readout/receiver.cxx
examples/region/sampler.cxx
examples/region/sink.cxx
fairmq/Device.cxx
fairmq/Device.h
fairmq/StateMachine.cxx
fairmq/Tools.h
fairmq/devices/BenchmarkSampler.h
fairmq/devices/Merger.h
fairmq/devices/Multiplier.h
fairmq/devices/Sink.h
fairmq/devices/Splitter.h
fairmq/tools/Exceptions.h
test/helper/devices/TestPollIn.h

Contributes to #372.
- Do not catch and re-throw exception from state handlers.
- feat: Add `Device::GetNumSubChannels(channel)`.
- Avoid accessing `Device::fChannels` directly, use getters.

Do not catch and rethrow exception from state handlers

---

fairmq/Channel.cxx
fairmq/Channel.h
fairmq/Device.h
fairmq/JSONParser.cxx
fairmq/Socket.h
fairmq/SuboptParser.cxx
fairmq/shmem/Socket.h
fairmq/zeromq/Common.h
fairmq/zeromq/Socket.h

- Add default send/receive timeout, configurable via `--channel-config` keys `sndTimeoutMs` and `rcvTimeoutMs`. Only affects default value (which is `-1` - no timeout - by default), when no explicit timeout argument is provided to Send/Receive.

Add configurable default snd/rcv timeout

---

fairmq/shmem/Manager.h
fairmq/shmem/UnmanagedRegion.h

Avoid shmem lock on region event checks & release lock sooner in the region initialization.

shm: reduce contention on region events

---

examples/region/keep-alive.cxx
fairmq/shmem/Manager.h

- Fix regression in region events handler (double unlock).
- shm: keep also the mng segment around when skipping cleanup.
- expand keep-alive example exe a bit.

Fix regression in region events handler

---

fairmq/plugins/control/Control.cxx
fairmq/plugins/control/Control.h

Provide a controller which is alike the static one but which does not transition to exit whenever it moves away from the Running state. This can be used to trigger transition from an external entity, e.g. the DPL debug GUI, hence the name.

GUI Controller

---

fairmq/zeromq/Common.h

In case IPC is used, we should not get the error, so better know about it.

Skip error message only for tcp

---

examples/region/sampler.cxx
fairmq/shmem/Manager.h
fairmq/shmem/Message.h

Fixes a race/deadlock in GetRegion/GetRegionInfo.

fix(shm): race/deadlock in region locks

---

examples/custom-controller/CMakeLists.txt
examples/custom-controller/MyController.h
examples/custom-controller/MyDevice.h
examples/custom-controller/main.cxx

New example demonstrating a simple custom controller (statically compiled into the executable) which executes a simple static plan through the state machine (similar to the built-in `--control static`). Builtin signal handling is disabled.

New example with a custom controller

---

meta_update.py

If .zenodo.json (or codemeta.json) isn't there, only throw a warning, and continue.
---
Checklist:

build(metaUpdater): Handle Non-Existant Files

---

codemeta.json
meta_update.py

* Fix Adding new creators to `.zenodo.json`
* Simplify Code a bit
* reorder `@id` to the top in codemeta.json
---
Checklist:

metaUpdater: Some Cleanups, Fixes

---

examples/region/keep-alive.cxx

Fixes a race in the keep-alive executable from the region example, which can lead to the segment presence check being run at the same time with the shmem reset call, this failing the check.

region example: fix race between segment reset & presence check

---

examples/region/sampler.cxx
fairmq/shmem/Manager.h
fairmq/shmem/UnmanagedRegion.h
fairmq/shmem/UnmanagedRegionImpl.h
test/region/_region.cxx

- Error on duplicate unmanaged region IDs.
- Extend debug output slightly.
- Add a test for externally (outside of a session) created shmem.

Shm: error on duplicate region IDs

---

fairmq/Channel.h
fairmq/Device.cxx

Fixes #454.
- Add `operator<<` to `fair::mq::Channel`.
- Extend error message if channel(s) was not configured before timeout.
- Cancel channel validation on pending state.

Extend invalid channel error

---

fairmq/shmem/Manager.h

When FairMQ is configured to try allocate a shmem message indefinitely, we might end up in a situation when a device is stuck without any information why it could be so. This log would help us understand why a device is stuck.

Warn when going to try allocate a shmem message more times

---

codemeta.json

GSI is providing resources for maintaining FairMQ. So let's document this in codemeta.json.
Codemeta < 4.0 does not allow anything but `Person`s in the `maintainer` field. I personally think, we should just ignore this.
---
Checklist:

codemeta: Add GSI as "maintainer"

---

fairmq/Message.h
fairmq/shmem/Message.h
fairmq/shmem/Socket.h
fairmq/zeromq/Message.h

- Move the members of MetaHeader flat into shmem::Message and sort them by size.
- Remove alignment member. Accept explicit argument for the method where it is needed (SetUsedSize), optionally. By default try to deduce reasonable alignment.
This reduces the size of shmem::Message from 92 bytes to 80 bytes. Two more members not clearly visible when skimming through the class are the this pointer, since we use virtual methods, and the member of the parent class - `fTransport`.

Refactor shmem::Message to reduce its size in memory

---

fairmq/Device.cxx
fairmq/tools/Process.cxx
fairmq/zeromq/Socket.h

Use std::move rather than just move
Apparently:
"warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]"
is default in new XCode.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/FairRootGroup/FairMQ/pull/487).
* __->__ #487
* #486

Use std::move rather than just move

---

examples/CMakeLists.txt
examples/region/fairmq-start-ex-region-advanced-external.sh.in
examples/region/fairmq-start-ex-region-advanced.sh.in
examples/region/fairmq-start-ex-region.sh.in
fairmq/shmem/Manager.h
fairmq/shmem/Monitor.cxx
fairmq/shmem/UnmanagedRegion.h

Fix a bug where the externally created region's rc segment settings would be ignored by the region user. The changes make sure that the registered size value is honored in case:
- region user creates it itself.
- region config is created externally (region user accepts external config value).
- region undergoes soft reset and is recreated by the region user (in this case the configured value still must be honored).
Other additions:
- Monitor output for the reference count segment to include the amount of free space in the segment.
- example script for usage with externally created regions.

Fix reference count region initialization

---

.github/workflows/check_metadata.yaml

If AUTHORS or CONTRIBUTORS are changed,
check that the changes are merged into codemeta.json, and .zenodo.json.
See: https://github.com/FairRootGroup/FairRoot/pull/1475
---
Checklist:

ci: Check codemeta/zenodo with AUTHORS/CONTRIBUTORS

---

fairmq/plugins/control/Control.cxx
test/device/_config.cxx

For #443.
Here I skip also the startup sequence. The plugin changes no states at all (device remains in Idle). Was that what we wanted to solve with this?
I've tested if the device still responds to signals with this and it does.

Add 'no control' controller

---

fairmq/CMakeLists.txt

Upon request by @ktf for access to `fair::mq::shmem::Message::GetRefCount()`.

Make shmem headers public
