Jenkinsfile, Jenkinsfile.nightly, fairmq/CMakeLists.txt, fairmq/FairMQStateMachine.cxx, fairmq/FairMQStateMachine.h, fairmq/options/FairMQParser.cxx, fairmq/options/FairMQParser.h, fairmq/plugins/DDS/DDS.cxx, fairmq/tools/Network.cxx, fairmq/tools/Network.h, fairmq/tools/Process.cxx, fairmq/tools/Process.h, fairmq/tools/Unique.cxx, fairmq/zeromq/FairMQMessageZMQ.cxx, fairmq/zeromq/FairMQSocketZMQ.cxx, test/device/TestReceiver.h, test/device/TestSender.h, test/helper/devices/TestPairLeft.cxx, test/helper/devices/TestPairRight.cxx, test/helper/devices/TestPollIn.cxx, test/helper/devices/TestPollOut.cxx, test/helper/devices/TestPull.cxx, test/helper/devices/TestPush.cxx, test/helper/devices/TestRep.cxx, test/helper/devices/TestReq.cxx
Hidden/forward declared boost msm, process, asio, uuid, property_tree headers. Fix for FairRootGroup/FairRoot#775.
=> Improve compilation speed

fairmq/FairMQChannel.cxx, fairmq/FairMQChannel.h
No need for buffer+size message on Receive.
---
Checklist:
=> Handle Send/Receive differently when switching transports

fairmq/FairMQDevice.cxx, fairmq/options/FairMQProgOptions.cxx, fairmq/plugins/DDS/DDS.cxx, fairmq/shmem/FairMQSocketSHM.cxx
=> Change unregistered options warning to debug

CONTRIBUTORS
To acknowledge his countless hours of consulting which benefited
this project significantly.
---
Checklist:
=> Add Matthias as CONTRIBUTOR

Dart.sh, FairMQTest.cmake, Jenkinsfile, fairmq/CMakeLists.txt
=> Add codecov reports to PRs

README.md
Also refactor the `Releases` section into top table in `README`
=> Add codecov badges

README.md
=> Fix variable name

fairmq/FairMQChannel.cxx, fairmq/FairMQDevice.cxx, fairmq/shmem/Monitor.cxx
- Apply clang-tidy suggestions [modernize-loop-convert]
- Apply clang-tidy suggestions [performance-faster-string-find]
---
Checklist:
=> Apply some clang-tidy suggestions

fairmq/FairMQChannel.cxx, fairmq/tools/Network.cxx, fairmq/tools/Network.h, test/CMakeLists.txt, test/channel/_channel.cxx, test/tools/_network.cxx
- Add test for interface IP detection tools
- Add test for channel validation
Also remove code duplication in network tools and fix wrong string size in channel validation.
---
Checklist:
=> Add tests for network tools and channel validation

fairmq/tools/Process.cxx
In the `execute` function from the process tools check for process validity and if it is running, before doing i/o with it.
---
Checklist:
=> Add safety checks for process tools

fairmq/FairMQSocket.h, fairmq/FairMQTransportFactory.h, fairmq/nanomsg/FairMQSocketNN.cxx, fairmq/nanomsg/FairMQSocketNN.h, fairmq/nanomsg/FairMQTransportFactoryNN.cxx, fairmq/nanomsg/FairMQTransportFactoryNN.h, fairmq/ofi/Socket.cxx, fairmq/ofi/Socket.h, fairmq/ofi/TransportFactory.cxx, fairmq/ofi/TransportFactory.h, fairmq/shmem/FairMQSocketSHM.cxx, fairmq/shmem/FairMQSocketSHM.h, fairmq/shmem/FairMQTransportFactorySHM.cxx, fairmq/shmem/FairMQTransportFactorySHM.h, fairmq/zeromq/FairMQSocketZMQ.cxx, fairmq/zeromq/FairMQSocketZMQ.h, fairmq/zeromq/FairMQTransportFactoryZMQ.cxx, fairmq/zeromq/FairMQTransportFactoryZMQ.h, test/protocols/_push_pull_multipart.cxx
This will set the transport factory pointer in messages received via the Recevie(std::vector...) (multipart) methods.
=> Factory pointer at receive

fairmq/shmem/FairMQSocketSHM.cxx
Fix -Wsign-compare warning
---
Checklist:
=> Fix -Wsign-compare warning

fairmq/MemoryResourceTools.h
containers are not required to allocate, e.g. small string optimization
For now this example is hypothetical since we cannot use std::basic_string with pmr
at least until gcc 7 since the basic_string there still uses the deprecated
rebind interface (which pmr does not implement). Probably good to have it in though.
=> Let getMessage deal with SSO

Jenkinsfile, Jenkinsfile.nightly
=> Add MacOS10.14 test machine to Jenkins

fairmq/FairMQDevice.cxx, fairmq/FairMQDevice.h, fairmq/StateMachine.cxx
Add backwards compatibility for removed ChangeState(int).
---
Checklist:
=> Add backwards compatibility for removed ChangeState(int)

fairmq/StateMachine.cxx, fairmq/StateMachine.h, fairmq/plugins/Control.cxx, test/CMakeLists.txt, test/device/_error_state.cxx, test/device/_exceptions.cxx, test/device/_signals.cxx, test/helper/devices/TestErrorState.h, test/helper/devices/TestSignals.h, test/helper/runTestDevice.cxx
- test raising SIGINT in every state
- test going to Error state from every state
- add new states (bind/connect) to exception tests
- remove obsolete state machine code
---
Checklist:
=> Extend tests of error cases

fairmq/tools/Process.cxx
Use Asio to launch processes in the tests and handle their I/O line by line.
---
Checklist:
=> Use Asio to launch processes in fair::mq::tools::execute

fairmq/tools/Process.cxx
Fix broken pipe errors in tools::execute
=> Fix broken pipe errors in tools::execute

fairmq/FairMQDevice.cxx
Notify all listeners on state changes
---
Checklist:
=> Notify all listeners on state changes

fairmq/PluginServices.h
for [this](https://github.com/FairRootGroup/FairMQ/issues/6#issuecomment-487011642).
---
Checklist:
=> Allow PluginServices::SetProperty in Ready state

fairmq/FairMQDevice.h
Very useful during deployment/setup
---
Checklist:
=> Print channel name in error log

fairmq/plugins/DDS/CMakeLists.txt
=> DDS plugin: Remove unused dependency

README.md, docs/Plugins.md
=> Docs: Add section about plugins

docs/Configuration.md, fairmq/FairMQChannel.h, fairmq/FairMQDevice.cxx, fairmq/FairMQDevice.h, fairmq/PluginServices.h, fairmq/ProgOptions.cxx, fairmq/ProgOptions.h, fairmq/nanomsg/FairMQTransportFactoryNN.cxx, fairmq/shmem/FairMQTransportFactorySHM.cxx, fairmq/zeromq/FairMQTransportFactoryZMQ.cxx, test/plugin_services/_config.cxx
- Add debug output in some destructors
- Clear channels & transports containers in Reset()
- Initialize initialization-timeout in InitWrapper()
- Move PropertyNotFound handling to ProgOptions
- Refactor some device code for better readability
- Extend configuration docs
---
Checklist:
=> More config docs & etc

fairmq/sdk/Topology.cxx, fairmq/sdk/Topology.h, test/sdk/_topology.cxx
SDK: Add test for timeout, concurrent call. Implement TODOs
---
Checklist:
=> SDK: Add test for timeout, concurrent call. Implement TODOs

CMakeLists.txt, examples/dds/CMakeLists.txt, examples/dds/fairmq-start-ex-dds.sh.in, fairmq/SDK.h, fairmq/sdk/CMakeLists.txt, fairmq/sdk/DDSAgent.h, fairmq/sdk/DDSSession.cxx, fairmq/sdk/DDSSession.h, fairmq/sdk/Topology.cxx, fairmq/sdk/Topology.h, test/sdk/Fixtures.h, test/sdk/_dds.cxx
Update SDK to use new DDS APIs:
`SAgentCountRequest`, `SAgentInfoRequest`.
Bump the required DDS version for the SDK.
---
Checklist:
=> Update SDK to use new DDS APIs

CMakeLists.txt
Print install prefix in cmake summary.
=> Print install prefix in cmake summary

CMakeLists.txt
=> Add support for fairlogger dependencies

.codecov.yml, fairmq/plugins/DDS/DDS.cxx, fairmq/plugins/DDS/DDS.h, fairmq/sdk/Topology.h
=> SDK: optimize TryChangeStateCompletion

fairmq/sdk/Topology.h
=> Use int instead of size_t for the state index container

CMakeLists.txt, fairmq/plugins/PMIx/PMIx.hpp, fairmq/plugins/PMIx/PMIxPlugin.cxx
Small changes/fixes from the tests last week.
=> Pmix update

README.md, docs/SDK.md
=> Docs: Add section on the Controller SDK

fairmq/FairMQDevice.h
Remove methods that were deprecated on 2018.10.31.
=> Remove deprecated methods

examples/dds/fairmq-start-ex-dds.sh.in, fairmq/Plugin.h, fairmq/PluginServices.cxx, fairmq/PluginServices.h, fairmq/plugins/DDS/DDS.cxx, fairmq/plugins/DDS/DDS.h, fairmq/plugins/DDS/runDDSCommandUI.cxx
- DDS plugin: remove static mode.
- DDSCommandUI: add support for more commands .
- Remove TransitionTo from plugin APIs.
=> Dds tools update

CMakeLists.txt, examples/dds/fairmq-start-ex-dds.sh.in, fairmq/sdk/DDSAgent.h, fairmq/sdk/DDSSession.cxx
=> Update to new DDS API, bump required version

CMakeLists.txt, Dart.sh, examples/dds/CMakeLists.txt, examples/dds/fairmq-start-ex-dds.sh.in, fairmq/CMakeLists.txt, fairmq/plugins/DDS/DDS.h, fairmq/plugins/DDS/runDDSCommandUI.cxx, fairmq/sdk/DDSEnvironment.cxx, fairmq/sdk/DDSSession.cxx, fairmq/sdk/DDSTopology.cxx, fairmq/sdk/Topology.cxx, test/sdk/_dds.cxx, test/sdk/_topology.cxx
=> Support and require DDS 3.0

.clang-tidy, cmake/FairMQLib.cmake, fairmq/MemoryResourceTools.h, fairmq/MemoryResources.cxx, fairmq/PluginManager.h, fairmq/ProgOptions.cxx, fairmq/plugins/DDS/DDS.cxx, fairmq/plugins/DDS/DDS.h, fairmq/sdk/AsioAsyncOp.h, fairmq/sdk/DDSSession.cxx, fairmq/sdk/DDSSession.h, fairmq/sdk/DDSTopology.cxx, fairmq/sdk/DDSTopology.h, fairmq/sdk/Error.cxx, fairmq/sdk/Error.h, fairmq/sdk/Topology.h, fairmq/sdk/commands/Commands.cxx, fairmq/sdk/commands/Commands.h, fairmq/sdk/commands/CommandsFormat.fbs, test/commands/_commands.cxx, test/sdk/_topology.cxx
=> First round on a SDK property API

CMakeLists.txt, CONTRIBUTORS, examples/dds/CMakeLists.txt, examples/dds/fairmq-ex-dds-env.sh
- For macOS append Boost_LIBRARY_DIRS to DYLD_LIBRARY_PATH and export DYLD_LIBRARY_PATH in the fairmq-ex-dds-env.sh
- Update CONTRIBUTORS list
Resolves #235 
---
Checklist:
=> Fix env script for DDS example

fairmq/sdk/DDSEnvironment.cxx
Fixes #235
@AndreyLebedev Could you please confirm this resolves #235?
=> SDK: Support DYLD_LIBRARY_PATH from parent env in `sdk::DDSEnv`

fairmq/plugins/PMIx/PMIxPlugin.cxx
=> PMIx plugin: adapt to updated commands format

fairmq/shmem/Socket.cxx, fairmq/zeromq/FairMQSocketZMQ.cxx
For AliceO2Group/AliceO2#3023.
=> Do not report interruption by system call as error

fairmq/shmem/Socket.cxx
=> Throw an error if shmem receives invalid meta data

examples/README.md, examples/dds/CMakeLists.txt, examples/n-m/CMakeLists.txt, examples/n-m/Header.h, examples/n-m/README.md, examples/n-m/ex-n-m-pair-topology.xml, examples/n-m/ex-n-m-topology.xml, examples/n-m/fairmq-ex-n-m-env.sh, examples/n-m/fairmq-start-ex-n-m-dds.sh.in, examples/n-m/fairmq-start-ex-n-m-pair-dds.sh.in, examples/n-m/fairmq-start-ex-n-m-pair.sh.in, examples/n-m/fairmq-start-ex-n-m.sh.in, examples/n-m/runReceiver.cxx, examples/n-m/runSender.cxx, examples/n-m/runSynchronizer.cxx, examples/qc/CMakeLists.txt, examples/qc/README.md, fairmq/plugins/DDS/DDS.cxx, fairmq/plugins/DDS/DDS.h
=> Add example and test of a n-to-m topology, incuding sub-channel use

cmake/FairMQLib.cmake, fairmq/PluginManager.cxx, fairmq/PluginManager.h
=> DeviceRunner: Extend lifetime of PluginManager beyond ProgOptions

fairmq/shmem/Manager.cxx, fairmq/shmem/Region.cxx
Thanks to @ironMann for the hint. Please let me know if this solves the issue for you.
=> Truncate the file used for the region mapping

fairmq/shmem/Message.h
=> Shm: fix incorrect ptr range check

fairmq/FairMQMessage.h, fairmq/FairMQSocket.h
=> Add missing includes

fairmq/ofi/Socket.h
Describe your proposal.
Mention any issue this PR resolves or is related to.
---
Checklist:
=> ofi: adapt to the new API for FairMQSocket::Events

CMakeLists.txt, fairmq/CMakeLists.txt, fairmq/shmem/Monitor.cxx, fairmq/shmem/runMonitor.cxx
=> ShmMonitor: Use FairLogger for timestamp calculation

examples/n-m/ex-n-m-pair-topology.xml, examples/n-m/ex-n-m-topology.xml
=> Fix tag mismatch in topology files

CMakeLists.txt, fairmq/sdk/AsioAsyncOp.h, fairmq/sdk/AsioBase.h
=> Bump asio to 1.18.0

fairmq/shmem/Manager.h
Fixes the case when region subscriptions locate existing shared memory segment that does not yet have corresponding transport-local metadata initialized (fixed by retrieving the missing data in such a case).
=> shm: ensure local segments are complete for region subscriptions

fairmq/shmem/Monitor.cxx
Fix regression introduced in v1.4.30.
=> Fix regression in shmmonitor

FairMQTest.cmake, Jenkinsfile, cmake/FairMQLib.cmake, fairmq/CMakeLists.txt, fairmq/shmem/Monitor.cxx
=> Fallback to <boost/filesystem> on GCC 7

fairmq/shmem/Manager.h, test/region/_region.cxx
Improve lookup and cache locality of shm Manager.
---
Checklist:
=> Thread local cache for Region lookup

fairmq/ofi/Socket.h, fairmq/ofi/TransportFactory.h
=> Fix Ofi interface

fairmq/shmem/Monitor.cxx, fairmq/shmem/Monitor.h, test/CMakeLists.txt, test/transport/_shmem.cxx
=> shm: add monitor method to retrieve free segment memory

cmake/FairMQProjectSettings.cmake, fairmq/shmem/Common.h, fairmq/shmem/Manager.h, fairmq/shmem/Monitor.cxx, fairmq/shmem/Monitor.h, fairmq/shmem/README.md
- set `CMAKE_EXPORT_COMPILE_COMMANDS` unconditionally
- shm: optimize monitor heartbeats mechanism
- shm: improve exception handling
- shm: throw TransportError if could not lock region
=> Shm optimizations

fairmq/shmem/Monitor.cxx
=> shmmonitor: handle missing segmentInfos

fairmq/CMakeLists.txt, fairmq/FwdDecls.h, fairmq/MemoryResources.h
=> more fixes

fairmq/Message.h, fairmq/shmem/Common.h, fairmq/shmem/Manager.h, fairmq/shmem/Message.h, test/CMakeLists.txt, test/message/_message.cxx, test/region/_region.cxx
Usage:
```C++
MessagePtr original(factory->CreateMessage(size));
// ...
MessagePtr copy(factory->CreateMessage());
copy->Copy(*original);
```
Also add tests and docs for it.
=> Implement shared message ownership for shmem transport

fairmq/Device.h
and deprecate those interfaces.
=> fix: -Winfinite-recursion

fairmq/CMakeLists.txt
=> fix: install tools/Exceptions.h

fairmq/shmem/UnmanagedRegion.h, test/region/_region.cxx
When opening a region with an id, the provided size should match the size of the opened region.
=> shm: check region size when opening existing

fairmq/shmem/Manager.h
- Shm: Fix number of region events, which has been incremented more often than it should, leading to unnecessary shm contention by the event thread.
- Shm: Recent patches removed shm lock from parts of Region handling (`fair::mq::shmem::Manager::fRegion`). However some of it still needs process-local thread-safety. Add it for the relevant parts.
=> Shm Patches

meta_update.py
* If an already existing entry in the json file has the correct ORCID, prefer it for updating, always
* Find that entry for codemeta as well
---
Checklist:
=> build: Match on ORCID in Updater

fairmq/shmem/Manager.h
- fix(shm): Fix incorrect parameters when mapping regions
=> fix(shm): Fix incorrect parameters when mapping regions

AUTHORS
cc: @MohammadAlTurany
---
Checklist:
=> Add ORCiD for @MohammadAlTurany

.github/workflows/fair-software.yml, examples/n-m/receiver.cxx, fairmq/Parts.h, fairmq/devices/Multiplier.h, test/CMakeLists.txt, test/parts/_add_part.cxx
=> Improve parts

fairmq/shmem/UnmanagedRegion.h
=> Fix unused value

test/message/_message.cxx, test/protocols/_push_pull_multipart.cxx
Such as:
https://cdash.gsi.de/viewTest.php?onlyfailed&buildid=416202
=> Fix address clashes in tests

.github/workflows/codemeta_validate.yaml
=> chore: upgrade checkout step to v4
